markdown: redcarpet
exclude: ['README.md', 'LICENCE.md']

title: Luis Loyola
url: 'http://luisloyola.github.io'
baseurl: '/luisloyola.github.io' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Luis Loyola
tagline: Desarrollador
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: luis.loyola.vidal@gmail.com
phone: +56 9 62204311
#website: blog.webjeda.com #do not add http://
linkedin: luis-loyola
github: luisloyola
#twitter: '@luisloyola'


# Tracker
analytics: UA-83979019-1
#Update all the sections by editing the files inside _includes folder.
